# Stage 1: Build with Maven
FROM maven:3.9.6-eclipse-temurin-17 AS builder

WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Stage 2: Tomcat + deploy WAR
FROM tomcat:10.1.20-jdk17-temurin

RUN rm -rf /usr/local/tomcat/webapps/*
COPY --from=builder /app/target/*.war /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]




# # ----------------------
# # Stage 1: Build with Maven (Builder Image)
# # ----------------------
# FROM maven:3.9.9-eclipse-temurin-17 AS builder

# WORKDIR /app

# # Clone only the required branch directly (best practice)
# RUN git clone --branch main --single-branch https://github.com/Ahmedlekan/springboot-pipeline.git

# WORKDIR /app/devops-project

# # Clean and build application (skip tests to speed up CI build)
# RUN mvn --batch-mode clean package -DskipTests

# # ----------------------
# # Stage 2: Tomcat + deploy artifact (Final runtime Image)
# # ----------------------
# FROM tomcat:10.1.20-jre17

# # Remove default apps to keep image smaller
# RUN rm -rf /usr/local/tomcat/webapps/*

# # Copy only the final WAR from builder (no source code, no Maven, no Git)
# COPY --from=builder /app/devops-project/target/*vprofile-v2.war /usr/local/tomcat/webapps/ROOT.war

# # Clean additional Tomcat docs/example apps
# RUN rm -rf /usr/local/tomcat/webapps/docs \
#     /usr/local/tomcat/webapps/examples \
#     /usr/local/tomcat/webapps/manager \
    
# # Expose Tomcat port
# EXPOSE 8080

# # Start Tomcat when container runs
# CMD ["catalina.sh", "run"]





